### ISSUE TITLE
Patched bgfx_compile_shader_to_header tramples output files with multiple fragment/vertex shaders.

### ISSUE THREAD

**Issue by DylanLukes** [Paper-Cranes-Ltd/big2-stack#1]
The patched version of `bgfx_compile_shader_to_header` does not work properly when there are multiple shaders of the same type (e.g. `fs_pass1.sc`, `fs_pass2.sc`, etc). The resulting contents of `ARGS_OUT_FILES_VAR` will only contain paths for _one_ input shader, rather than all of them.

This is due to the following trampling the previous contents of `ARGS_OUT_FILES_VAR` here:

https://github.com/Paper-Cranes-Ltd/big2-stack/blob/a2d01c42a8f66d120e1621a3600ef60d1aee7a30/patches/bgfx-cmake.patch#L80-L82

To fix this, I changed this in my version of this patch to the following:

```diff
+		if(DEFINED ARGS_OUT_FILES_VAR)
+			list(APPEND ${ARGS_OUT_FILES_VAR} ${OUTPUTS})
+			set(${ARGS_OUT_FILES_VAR} ${${ARGS_OUT_FILES_VAR}} PARENT_SCOPE)
+		endif()
```

– Dylan

**Comment by object71** [comment]
Fixed in v0.1.3 onwards by a patch. Still waiting for the original pull request in bgfx.cmake
