### ISSUE TITLE
example 03 & 04 not work in windows 11( bgfx init failed )

### ISSUE THREAD

**Issue by wsAndy** [Paper-Cranes-Ltd/big2-stack#3]
in 03_multiple_windows.cpp, the following code blocks cause bgfx error as "BX_TRACE("Initializing headless mode, resolution of non-existing backbuffer can't be larger than 0x0!");"
```
  bgfx::Init init_object;
  big2::Validate(bgfx::init(init_object), "BGFX couldn't be initialized");
```

**Comment by object71** [comment]
Bgfx doesn't support mutliple windows on some renderers. I added code that avoids the crash but it still remains unsupported. This can be brought up to the BGFX repository since it should be supported by renderers like vulkan.
